filebeat.inputs:

  - input_type: log
    paths:
      - /var/log/json*.log*
    tags: ["json"]
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
